"$schema" = "node_modules/wrangler/config-schema.json"

account_id = "1766f35ec0dc9e97a6f153e46dbec6ba"
name = "roxys-gateway"
compatibility_date = "2025-06-02"
main = "./src/main.ts"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[vars]
UPSTREAM_URL = "http://localhost:3000"

[[vpc_services]]
binding = "VPC_PAN"
service_id = "019f652a-973f-73d0-93a0-cbe544dde600"
remote = true
